### ISSUE TITLE
Address already in use while running second time

### ISSUE THREAD

**Issue by Srutsth** [yangkky/distributed_tutorial#13]
Thanks for the tutorial. So I did accoding to the tutorial but I got error at 
Training does not happen.. 
I ran the script from two terminal, and both the places hangs, seems like they are waiting for something

**Comment by linminhtoo** [comment]
> Thanks for the tutorial. So I did accoding to the tutorial but I got error at Training does not happen.. I ran the script from two terminal, and both the places hangs, seems like they are waiting for something

You can just try a different address.

**Comment by Srutsth** [comment]
But then wont they need to initilaize in same port to see what the other process are and to accumulate stuffs?

**Comment by linminhtoo** [comment]
> But then wont they need to initilaize in same port to see what the other process are and to accumulate stuffs?

If the first training got stuck, you can try to kill all the process related to it. From my experience on 1 machine 8 GPUs, just killing the main process is enough to kill everything. Once you confirm the GPU usage is 0% on all GPUs, you can try again. If it stil complains the address is used, just try a different address.

**Comment by linminhtoo** [comment]
The program distributes the address and other needed info under the hood to all the GPUs from the master process.
